import { User } from "../interfaces/auth.interface";

export const mockUsers: User[] = [
  {
    id: 1,
    nome: "Carlos Andrade",
    matricula: "10001",
    senha: "admin123",
    funcionalidade: "Diretor",
  },
  {
    id: 2,
    nome: "Helena Costa",
    matricula: "10002",
    senha: "admin456",
    funcionalidade: "Diretor",
  },

  {
    id: 3,
    nome: "Erasmo Carlos",
    matricula: "20001",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 4,
    nome: "Luís Sierra",
    matricula: "20002",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 5,
    nome: "Marcos Oliveira",
    matricula: "20003",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 6,
    nome: "Ana Beatriz",
    matricula: "20004",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 7,
    nome: "Ricardo Lima",
    matricula: "20005",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 8,
    nome: "Fernanda Souza",
    matricula: "20006",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 9,
    nome: "Gustavo Mendes",
    matricula: "20007",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 10,
    nome: "Patrícia Alves",
    matricula: "20008",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 11,
    nome: "Rafaela Borges",
    matricula: "20009",
    senha: "senha123",
    funcionalidade: "Professor",
  },
  {
    id: 12,
    nome: "Sérgio Rocha",
    matricula: "20010",
    senha: "senha123",
    funcionalidade: "Professor",
  },

  {
    id: 13,
    nome: "Lucas Souza",
    matricula: "24001",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 14,
    nome: "Júlia Santos",
    matricula: "24002",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 15,
    nome: "Pedro Oliveira",
    matricula: "24003",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 16,
    nome: "Beatriz Costa",
    matricula: "24004",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 17,
    nome: "Gabriel Pereira",
    matricula: "24005",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 18,
    nome: "Mariana Almeida",
    matricula: "24006",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 19,
    nome: "Matheus Rodrigues",
    matricula: "24007",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 20,
    nome: "Isabella Lima",
    matricula: "24008",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 21,
    nome: "Rafael Ferreira",
    matricula: "24009",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 22,
    nome: "Sofia Gomes",
    matricula: "24010",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 23,
    nome: "Felipe Martins",
    matricula: "24011",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 24,
    nome: "Manuela Ribeiro",
    matricula: "24012",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 25,
    nome: "Bruno Alves",
    matricula: "24013",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 26,
    nome: "Laura Carvalho",
    matricula: "24014",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 27,
    nome: "Gustavo Dias",
    matricula: "24015",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 28,
    nome: "Alice Rocha",
    matricula: "24016",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 29,
    nome: "Guilherme Barbosa",
    matricula: "24017",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 30,
    nome: "Valentina Mendes",
    matricula: "24018",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 31,
    nome: "Leonardo Nunes",
    matricula: "24019",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 32,
    nome: "Heloísa Fernandes",
    matricula: "24020",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 33,
    nome: "Vinícius Moreira",
    matricula: "24021",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 34,
    nome: "Gabriela Correia",
    matricula: "24022",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 35,
    nome: "Davi Lopes",
    matricula: "24023",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 36,
    nome: "Clara Barros",
    matricula: "24024",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 37,
    nome: "Arthur Cardoso",
    matricula: "24025",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 38,
    nome: "Yasmin Pinto",
    matricula: "24026",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 39,
    nome: "Caio Teixeira",
    matricula: "24027",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 40,
    nome: "Lívia Nogueira",
    matricula: "24028",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 41,
    nome: "Eduardo Azevedo",
    matricula: "24029",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },
  {
    id: 42,
    nome: "Lorena Cunha",
    matricula: "24030",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 1,
  },

  {
    id: 43,
    nome: "Enzo Farias",
    matricula: "24031",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 44,
    nome: "Amanda Maciel",
    matricula: "24032",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 45,
    nome: "Miguel Melo",
    matricula: "24033",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 46,
    nome: "Letícia Ramos",
    matricula: "24034",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 47,
    nome: "Heitor Castro",
    matricula: "24035",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 48,
    nome: "Ana Clara Viana",
    matricula: "24036",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 49,
    nome: "Bernardo Duarte",
    matricula: "24037",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 50,
    nome: "Cecília Freire",
    matricula: "24038",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 51,
    nome: "Davi Lucas Moraes",
    matricula: "24039",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 52,
    nome: "Esther Campos",
    matricula: "24040",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 53,
    nome: "Lorenzo Brandão",
    matricula: "24041",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 54,
    nome: "Elisa Silveira",
    matricula: "24042",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 55,
    nome: "Théo Pires",
    matricula: "24043",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 56,
    nome: "Sarah Rezende",
    matricula: "24044",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 57,
    nome: "Isaac Portela",
    matricula: "24045",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 58,
    nome: "Luiza Siqueira",
    matricula: "24046",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 59,
    nome: "Benjamin Arantes",
    matricula: "24047",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 60,
    nome: "Melissa Paiva",
    matricula: "24048",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 61,
    nome: "Erick Vasconcelos",
    matricula: "24049",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 62,
    nome: "Nicole Bezerra",
    matricula: "24050",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 63,
    nome: "Samuel Fontes",
    matricula: "24051",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 64,
    nome: "Rebeca Dantas",
    matricula: "24052",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 65,
    nome: "Nicolas Leal",
    matricula: "24053",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 66,
    nome: "Marina Frota",
    matricula: "24054",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 67,
    nome: "Daniel Peixoto",
    matricula: "24055",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 68,
    nome: "Isis Amorim",
    matricula: "24056",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 69,
    nome: "Joaquim Tavares",
    matricula: "24057",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 70,
    nome: "Alana Xavier",
    matricula: "24058",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 71,
    nome: "Fernando Drummond",
    matricula: "24059",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },
  {
    id: 72,
    nome: "Catarina Queiroz",
    matricula: "24060",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 2,
  },

  {
    id: 73,
    nome: "Antônio Neves",
    matricula: "24061",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 74,
    nome: "Helena Sales",
    matricula: "24062",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 75,
    nome: "Francisco Lacerda",
    matricula: "24063",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 76,
    nome: "Lavínia Bentes",
    matricula: "24064",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 77,
    nome: "Ryan Pimentel",
    matricula: "24065",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 78,
    nome: "Vitória Guedes",
    matricula: "24066",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 79,
    nome: "Igor Assis",
    matricula: "24067",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 80,
    nome: "Bianca Cordeiro",
    matricula: "24068",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 81,
    nome: "Carlos Eduardo Braga",
    matricula: "24069",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 82,
    nome: "Emilly Fogaça",
    matricula: "24070",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 83,
    nome: "Murilo Damasceno",
    matricula: "24071",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 84,
    nome: "Maria Eduarda Franco",
    matricula: "24072",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 85,
    nome: "Breno Pantoja",
    matricula: "24073",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 86,
    nome: "Rafaela Chaves",
    matricula: "24074",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 87,
    nome: "Vitor Hugo Mourão",
    matricula: "24075",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 88,
    nome: "Maria Luiza Guimarães",
    matricula: "24076",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 89,
    nome: "Lucca Barreto",
    matricula: "24077",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 90,
    nome: "Agatha Leitão",
    matricula: "24078",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 91,
    nome: "Cauã Dorneles",
    matricula: "24079",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 92,
    nome: "Isadora Pacheco",
    matricula: "24080",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 93,
    nome: "Henry Valente",
    matricula: "24081",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 94,
    nome: "Maria Alice Simões",
    matricula: "24082",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 95,
    nome: "Marcos Vinícius Trindade",
    matricula: "24083",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 96,
    nome: "Ana Luiza Veras",
    matricula: "24084",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 97,
    nome: "Otávio Galvão",
    matricula: "24085",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 98,
    nome: "Clarice Teles",
    matricula: "24086",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 99,
    nome: "Augusto Caldeira",
    matricula: "24087",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 100,
    nome: "Gabrielly Arruda",
    matricula: "24088",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 101,
    nome: "Noah Castanheira",
    matricula: "24089",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },
  {
    id: 102,
    nome: "Stella Furtado",
    matricula: "24090",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 3,
  },

  {
    id: 103,
    nome: "José da Mota",
    matricula: "24091",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 104,
    nome: "Pietra Benevides",
    matricula: "24092",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 105,
    nome: "Luiz Felipe Zagallo",
    matricula: "24093",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 106,
    nome: "Maya Bittencourt",
    matricula: "24094",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 107,
    nome: "André Vasques",
    matricula: "24095",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 108,
    nome: "Ana Beatriz Quintela",
    matricula: "24096",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 109,
    nome: "Thiago Gusmão",
    matricula: "24097",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 110,
    nome: "Maria Cecília Salgado",
    matricula: "24098",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 111,
    nome: "Kaique Novais",
    matricula: "24099",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 112,
    nome: "Ana Vitória Falcão",
    matricula: "24100",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 113,
    nome: "Yuri Lins",
    matricula: "24101",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 114,
    nome: "Liz Meireles",
    matricula: "24102",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 115,
    nome: "Bryan Saboia",
    matricula: "24103",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 116,
    nome: "Olívia Portes",
    matricula: "24104",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 117,
    nome: "Rodrigo Gurgel",
    matricula: "24105",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 118,
    nome: "Antonella Tavares",
    matricula: "24106",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 119,
    nome: "Renan Montenegro",
    matricula: "24107",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 120,
    nome: "Maria Helena Barroso",
    matricula: "24108",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 121,
    nome: "Emanuel Pinheiro",
    matricula: "24109",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 122,
    nome: "Ayla Farias",
    matricula: "24110",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 123,
    nome: "Diego Escobar",
    matricula: "24111",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 124,
    nome: "Ana Laura Távora",
    matricula: "24112",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 125,
    nome: "Luan Gadelha",
    matricula: "24113",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 126,
    nome: "Aurora Aguiar",
    matricula: "24114",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 127,
    nome: "Enrico Benevides",
    matricula: "24115",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 128,
    nome: "Laura Guedes",
    matricula: "24116",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 129,
    nome: "Nathan Sampaio",
    matricula: "24117",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 130,
    nome: "Isabelly Cordeiro",
    matricula: "24118",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 131,
    nome: "Victor Nogueira",
    matricula: "24119",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
  {
    id: 132,
    nome: "Luna Castelo",
    matricula: "24120",
    senha: "aluno",
    funcionalidade: "Aluno",
    turmaId: 4,
  },
];
